sudo: false
addons:
  jwt:
    secure: egTo2EERSKVWdBoP+6ewd/JIyyly2XTT1xOVj27v2L148c453uRNPjXwiGRYu7vTw5rkGK+H54n4FG3rUOuEVNX9NDNC5TlkhTfmecXNzjyOIuV7xD0qg5s6Q3IXg8kAp9+JXWbVVR6hoPzmAAnTT4rcoh6cPg4Tf327W2sRGkw=
env:
  global:
  - SAUCE_USERNAME=none
  - TRAVIS_NODE_VERSION="4.2"
matrix:
  include:
  - env: PLATFORM=ios-9.3
    os: osx
    osx_image: xcode7.3
    language: node_js
    node_js: $TRAVIS_NODE_VERSION
  - env: PLATFORM=ios-10.0
    os: osx
    osx_image: xcode7.3
    language: node_js
    node_js: $TRAVIS_NODE_VERSION
  - env: PLATFORM=android-19
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
  - env: PLATFORM=android-21
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
  - env: PLATFORM=android-23
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
  - env: PLATFORM=android-24
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- npm cache clean -f
- node --version
- if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
- if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
- if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-19,android-22,android-23,android-24,android-25;
  fi
- if [[ "$PLATFORM" =~ android ]]; then android create avd --force -n test --abi armeabi-v7a -t $PLATFORM;
  fi
- if [[ "$PLATFORM" =~ android ]]; then emulator -avd test -no-audio -no-window;
  fi
- if [[ "$PLATFORM" =~ android ]]; then circle-android wait-for-boot
- npm install -g cordova
install:
- npm install
script:
- npm test
- npm run cordova-paramedic